# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/src/conf.py

# we need mpi-sppy for automodule
python:
  version: 3.9
  install:
    - method: setuptools
      path: .
