#!/bin/bash

#SBATCH -N 1
#SBATCH -J 3scen_fw_cross
#SBATCH -t 00:30:00
#SBATCH -p pbatch
#SBATCH --mail-type=ALL
#SBATCH -A mpisppy

export MPICH_ASYNC_PROGRESS=1
source ${HOME}/venvs/mpisppy/bin/activate
cd ${HOME}/mpi-sppy/examples/uc

srun -n 15 python3 -u uc_cylinders.py --bundles-per-rank=0 --max-iterations=100 --default-rho=1.0 --num-scens=3 --max-solver-threads=2 --solver-name=gurobi_persistent --rel-gap=0.0001 --abs-gap=1 --intra-hub-conv-thres=-1.0 --fixer --lagrangian --xhatshuffle --fwph --cross-scenario-cuts
