#!/bin/bash

#SBATCH -N 5
#SBATCH -J 50scen_nofw_bundles
#SBATCH -t 00:10:00
#SBATCH -p pbatch
#SBATCH --mail-type=ALL
#SBATCH -A mpisppy

export MPICH_ASYNC_PROGRESS=1
source ${HOME}/python3.7/bin/activate
cd ${HOME}/mpi-sppy/examples/uc

srun -n 75 python3.7 uc_cylinders.py --bundles-per-rank=1 --max-iterations=100 --default-rho=1.0 --num-scens=50 --max-solver-threads=2 --solver-name=gurobi_persistent --rel-gap=0.0001 --no-fwph --no-cross-scenario-cuts 
