#!/bin/bash

#SBATCH -N 2
#SBATCH -J 5scen_fw_cross
#SBATCH -t 00:30:00
#SBATCH -p pbatch
#SBATCH --mail-type=ALL
#SBATCH -A mpisppy

export MPICH_ASYNC_PROGRESS=1
source ${HOME}/python3.7/bin/activate
cd ${HOME}/mpi-sppy/examples/uc

srun -n 25 unbuffer python3.7 uc_cylinders.py --bundles-per-rank=0 --max-iterations=100 --default-rho=1.0 --num-scens=5 --max-solver-threads=2 --solver-name=gurobi_persistent --rel-gap=0.00001 --abs-gap=1 --no-fixer
