#!/bin/bash

#SBATCH -N 64
#SBATCH -J 250scen_fw
#SBATCH -t 00:10:00
#SBATCH -p pbatch
#SBATCH --mail-type=ALL
#SBATCH -A mpisppy

export MPICH_ASYNC_PROGRESS=1
cd ${HOME}/mpi-sppy/paperruns/larger_uc
source ${HOME}/venvs/mpisppy/bin/activate

srun -n 1000 python3 -u uc_cylinders.py --bundles-per-rank=0 --max-iterations=100 --default-rho=1.0 --num-scens=250 --max-solver-threads=2 --solver-name=gurobi_persistent --rel-gap=0.00001 --abs-gap=1 --intra-hub-conv-thres=-1.0 --fixer --lagrangian --xhatshuffle --fwph
