name: No mpi4py (Pyomo released)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
    run:
        shell: bash -l {0}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test_env
          python-version: 3.8
          auto-activate-base: false
      - name: Install dependencies
        run: |
          pip install pyomo sphinx sphinx_rtd_theme cplex
          pip install xpress numpy pandas scipy dill

      - name: setup the program
        run: |
          python setup.py develop

      - name: PH EF tests
        run: |
          cd mpisppy/tests
          python test_ef_ph.py

