# Test the SchurComplement interface

name: schur-complement

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
    - uses: actions/checkout@v1
    - name: setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy nose pybind11
        conda install openmpi pymumps --no-update-deps
        pip install mpi4py pandas
        pip install git+https://github.com/pyutilib/pyutilib.git
        git clone https://github.com/pyomo/pyomo.git
        cd pyomo/
        python setup.py develop
        pyomo download-extensions
        pyomo build-extensions
        cd ../
        pip install git+https://github.com/parapint/parapint.git
        python setup.py develop
    - name: Test with nose
      run: |
        nosetests -v mpisppy/tests/test_sc.py
        mpirun -np 3 -oversubscribe nosetests mpisppy/tests/test_sc.py
