name: straight (Pyomo released)

# april 2023: matched the testaph.yml dependencies

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
    run:
        shell: bash -l {0}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test_env
          python-version: 3.9
          auto-activate-base: false
      - name: Install dependencies
        run: |
          conda install mpi4py pandas setuptools
          pip install pyomo xpress cplex dill

      - name: setup the program
        run: |
          python setup.py develop

      - name: mpi tests
        run: |
          cd mpisppy/tests
          python straight_tests.py

