# picked bundles (pyomo released)

name: pickled bundles tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
    run:
        shell: bash -l {0}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test_env
          python-version: 3.8
          auto-activate-base: false
      - name: Install dependencies
        run: |
          conda install mpi4py numpy setuptools 
          pip install pyomo pandas xpress cplex scipy sympy dill PyYAML Pympler networkx pandas

      - name: setup the program
        run: |
          python setup.py develop

      - name: run pickled bundles tests
        timeout-minutes: 10
        run: |
          cd mpisppy/tests
          python test_pickle_bundle.py 

